<?php
/**
* @var \Smile\Retailer\Block\RetailerData $block
*/
?>
<script type="text/x-magento-init">
<?php
    /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode([
        '*' => ['Smile_Retailer/js/retailer/data-provider' => [
            'apiBaseUrl' => $block->getApiBaseUrl('rest/V1/retailer/'),
            'cookieLifeTime' => $block->getCookieLifeTime()
        ]],
    ]);
?>
</script>
